"""
ACE State Management for LangGraph
Defines the TypedDict state structure for the ACE evolution loop.
"""

from typing import TypedDict, List, Dict, Any, Optional


class ACEState(TypedDict):
    """
    LangGraph State Definition for ACE Framework

    Tracks the complete evolution state including:
    - Current playbook (evolving context)
    - Generation metrics
    - Sample processing state
    - Historical best results
    """

    # ============================================================================
    # Core Evolution State
    # ============================================================================
    current_playbook: Dict[str, List[str]]
    """Current evolving playbook with categorized strategies"""

    generation_index: int
    """Current generation number in the evolution loop"""

    fitness_score: float
    """Current fitness score (accuracy on validation set)"""

    error_samples: List[Dict[str, Any]]
    """Top 3-5 error samples for refinement (stored per paper requirement)"""

    # ============================================================================
    # Sample Processing State
    # ============================================================================
    current_sample: Dict[str, Any]
    """Current sample being processed"""

    ground_truth: Any
    """Ground truth answer for current sample"""

    generated_answer: Any
    """Answer generated by the Generator node"""

    generator_trace: str
    """Reasoning trace from the Generator"""

    # ============================================================================
    # Reflector Output
    # ============================================================================
    reflection: Dict[str, Any]
    """Reflection output from Reflector node containing:
    - reasoning: analysis of what went wrong
    - error_identification: specific error
    - root_cause_analysis: why the error occurred
    - correct_approach: what should have been done
    - key_insight: principle to remember
    """

    # ============================================================================
    # Configuration
    # ============================================================================
    max_generations: int
    """Maximum number of generations before stopping"""

    plateau_threshold: int
    """Stop after this many consecutive generations without improvement"""

    max_playbook_size: int
    """Maximum token budget for playbook (prevents context overflow)"""

    # ============================================================================
    # Historical Best (for rollback)
    # ============================================================================
    best_playbook: Dict[str, List[str]]
    """Best playbook seen so far"""

    best_score: float
    """Best fitness score achieved"""

    no_improvement_count: int
    """Count of consecutive generations without improvement"""

    # ============================================================================
    # Training Progress
    # ============================================================================
    current_epoch: int
    """Current training epoch"""

    total_epochs: int
    """Total number of training epochs"""

    samples_processed: int
    """Number of samples processed in current epoch"""

    total_samples: int
    """Total number of training samples"""

    # ============================================================================
    # Evaluation State
    # ============================================================================
    validation_results: List[Dict[str, Any]]
    """Results from latest validation pass"""

    last_validation_at: int
    """Generation index of last validation"""


def initialize_state(
    config: Optional[Dict[str, Any]] = None
) -> ACEState:
    """
    Initialize a new ACEState with default values.

    Args:
        config: Optional configuration dict to override defaults

    Returns:
        Initialized ACEState dict
    """
    config = config or {}

    # Initial playbook for FINER sequence labeling
    initial_playbook = {
        "strategies_and_hard_rules": [
            "Determine the task is sequence labeling and output a tag for every token.",
            "Final answer must be a JSON array of tags with the same length as the token list.",
            "Tag tokens in order; do not add or omit tokens.",
            "Do not assume header/metadata is all 'O'—still scan for entity mentions.",
            "Use B- and I- tags consistently for multi-token entities.",
        ],
        "formulas_and_calculations": [],
        "verification_checklist": [
            "Check tag sequence length equals token count.",
            "Verify tags are valid FINER tags (e.g., O, B-*, I-*).",
            "Ensure entity spans use correct B-/I- transitions.",
        ],
        "common_mistakes": [
            "Do not output natural language analysis instead of tag sequences.",
            "Do not output tags with missing or extra tokens.",
        ],
        "apis_to_use_for_specific_information": [],
    }

    return ACEState(
        # Core Evolution State
        current_playbook=initial_playbook,
        generation_index=0,
        fitness_score=0.0,
        error_samples=[],

        # Sample Processing State
        current_sample={},
        ground_truth=None,
        generated_answer=None,
        generator_trace="",

        # Reflector Output
        reflection={},

        # Configuration
        max_generations=config.get("max_generations", 10),
        plateau_threshold=config.get("plateau_threshold", 3),
        max_playbook_size=config.get("max_playbook_size", 10000),

        # Historical Best
        best_playbook=initial_playbook.copy(),
        best_score=0.0,
        no_improvement_count=0,

        # Training Progress
        current_epoch=0,
        total_epochs=config.get("total_epochs", 5),
        samples_processed=0,
        total_samples=config.get("total_samples", 1000),

        # Evaluation State
        validation_results=[],
        last_validation_at=0,
    )


def copy_playbook(playbook: Dict[str, List[str]]) -> Dict[str, List[str]]:
    """
    Create a deep copy of a playbook.

    Args:
        playbook: Source playbook to copy

    Returns:
        Deep copy of the playbook
    """
    return {k: v.copy() for k, v in playbook.items()}


def state_to_dict(state: ACEState) -> Dict[str, Any]:
    """
    Convert ACEState to a regular dict for serialization.

    Args:
        state: ACEState to convert

    Returns:
        Regular dict representation
    """
    return dict(state)
